update intel 19.0.5 PR build to cxx17
trilinos/Trilinos pull request #11163
Opened 2022-10-19 21:44 UTC by fryeguy52

@trilinos/framework 

## Motivation
This is updating the cxx standard from 14 to 17 on the intel 19 build

2022-10-19 21:54 UTC, e10harvey commented
@fryeguy52 : can you please move this to target https://github.com/e10harvey/Trilinos/tree/sprint17_cpp17 instead?

2022-10-20 13:22 UTC, e10harvey requested changes

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +#opt-set-cmake-var Netcdf_INCLUDE_DIRS PATH : ${SEMS_NETCDF_INCLUDE_PATH|ENV}
Please revert. This will affect all builds.

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +#opt-set-cmake-var TPL_Netcdf_LIBRARIES STRING : ${SEMS_NETCDF_LIBRARY_PATH|ENV}/libnetcdf.so;${SEMS_NETCDF_LIBRARY_PATH|ENV}/libpnetcdf.a
Same as above.

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +# LINK_JOBS_LIMIT only has an affect when CMAKE_GENERATOR=Ninja, default to 2
Does this break anything using `COMMON_SPACK_TPLS`?

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +#opt-set-cmake-var TPL_Boost_LIBRARIES    STRING : ${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_program_options.a;${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_system.a
Please revert. You can add a new lib-type section instead.

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +#opt-set-cmake-var TPL_Boost_LIBRARIES    STRING : ${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_program_options.so;${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_system.so
Same as above.

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +opt-set-cmake-var TPL_Boost_LIBRARIES    STRING : ${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_program_options.a;${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_system.a
This is not `use`d below.

2022-10-20 13:22 UTC, e10harvey commented on packages/framework/ini-files/config-specs.ini
> +opt-set-cmake-var TPL_Boost_LIBRARIES    STRING : ${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_program_options.so;${SEMS_BOOST_LIBRARY_PATH|ENV}/libboost_system.so
Not `use`d below.

2022-12-13 15:50 UTC, sebrowne commented
@fryeguy52, we can close this given the lack of 19.0.5 testing, no?

2023-03-15 13:25 UTC, sebrowne commented
@fryeguy52 can we close this?

2024-01-03 21:03 UTC, sebrowne commented
All builds are now at C++17, no longer necessary

2024-01-03 21:03 UTC, closed without merging