Ifpack2: Add the option to pass the number of sublines per line inside a parameterlist
trilinos/Trilinos pull request #12591
Opened 2023-12-06 20:46 UTC by kliegeois

Add the option to pass the number of sublines per line inside a parameterlist

@trilinos/<teamName>

## Motivation

## Stakeholder Feedback

## Testing

2023-12-06 20:55 UTC, brian-kelley requested changes
This is minor but I just suggest that the parameter's name is consistent with the other partitioner options.

2023-12-06 20:55 UTC, brian-kelley commented on packages/ifpack2/src/Ifpack2_BlockRelaxation_def.hpp
> +  validParams->set("Number of subparts per part", 1);
Could this be named "partitioner: subparts per part"? That way it's easier to see where it's used when looking at an Ifpack2 parameter list

2023-12-06 21:43 UTC, kliegeois commented
Thanks a lot @brian-kelley for the review! I am updating the name right now.

2023-12-06 21:46 UTC, brian-kelley approved these changes

2023-12-08 06:12 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2023-12-08 08:49 UTC, trilinos-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ brian-kelley ]!

2023-12-08 08:49 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2023-12-08 08:49 UTC, merged

2023-12-08 08:49 UTC, trilinos-autotester commented
Merge on Pull Request# 12591: IS A SUCCESS - Pull Request successfully merged