Tpetra: enable SYCL matrix-matrix tests
trilinos/Trilinos pull request #13198
Opened 2024-07-02 20:51 UTC by cwpearson

The underlying issue appears to have been resolved a while ago - see https://github.com/kokkos/kokkos-kernels/issues/1062

2024-07-02 20:56 UTC, csiefer2 submitted a review, later dismissed

2024-07-02 21:04 UTC, brian-kelley commented
@cwpearson Are the spgemm related tests going to pass though, without #13052 merged or without MKL enabled?

2024-07-03 10:23 UTC, trilinos-autotester commented
Status Flag 'Master Merge AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi-openmp</h3>
<ul>
  <li>Build Num: 66</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc</h3>
<ul>
  <li>Build Num: 117</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi_debug</h3>
<ul>
  <li>Build Num: 118</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_clang</h3>
<ul>
  <li>Build Num: 117</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-clang-11.0.1-openmpi-4.0.5-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_PR_python3</h3>
<ul>
  <li>Build Num: 4076</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>BLOCKING_BUILD</td>
    <td>false</td>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_cuda</h3>
<ul>
  <li>Build Num: 117</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8-gpu</td>
  </tr>

  <t [...]

2024-07-04 10:22 UTC, trilinos-autotester commented
Status Flag 'Master Merge AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi-openmp</h3>
<ul>
  <li>Build Num: 77</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc</h3>
<ul>
  <li>Build Num: 128</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi_debug</h3>
<ul>
  <li>Build Num: 129</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_clang</h3>
<ul>
  <li>Build Num: 128</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-clang-11.0.1-openmpi-4.0.5-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_PR_python3</h3>
<ul>
  <li>Build Num: 4087</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>BLOCKING_BUILD</td>
    <td>false</td>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_cuda</h3>
<ul>
  <li>Build Num: 128</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8-gpu</td>
  </tr>

  <t [...]

2024-07-04 13:04 UTC, trilinos-autotester commented
Status Flag 'Master Merge AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 15 Mins. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi-openmp</h3>
<ul>
  <li>Build Num: 77</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc</h3>
<ul>
  <li>Build Num: 128</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi_debug</h3>
<ul>
  <li>Build Num: 129</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_clang</h3>
<ul>
  <li>Build Num: 128</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-clang-11.0.1-openmpi-4.0.5-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_PR_python3</h3>
<ul>
  <li>Build Num: 4087</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>BLOCKING_BUILD</td>
    <td>false</td>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Master Merge</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>master</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>77005adad6d625dbf62009620ffdc4ffa06b9fac</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_cuda</h3>
<ul>
  <li>Build Num: 128</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDAS [...]

2024-07-05 23:33 UTC, jhux2 requested changes
Should merge into `develop`.  Not sure why the autobot didn't flag this.

2024-07-10 15:11 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi-openmp</h3>
<ul>
  <li>Build Num: 97</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc</h3>
<ul>
  <li>Build Num: 148</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi_debug</h3>
<ul>
  <li>Build Num: 149</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_clang</h3>
<ul>
  <li>Build Num: 148</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-clang-11.0.1-openmpi-4.0.5-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_PR_python3</h3>
<ul>
  <li>Build Num: 4107</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>BLOCKING_BUILD</td>
    <td>false</td>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request (Non-blocking)</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_cuda</h3>
<ul>
  <li>Build Num: 148</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8-gp [...]

2024-07-10 17:57 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi-openmp</h3>
<ul>
  <li>Build Num: 97</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-openmp_release-debug_static_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc</h3>
<ul>
  <li>Build Num: 148</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_gcc-openmpi_debug</h3>
<ul>
  <li>Build Num: 149</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-gnu-8.5.0-openmpi-4.1.6-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_clang</h3>
<ul>
  <li>Build Num: 148</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-clang-11.0.1-openmpi-4.0.5-serial_release-debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_mpi_no-pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_PR_python3</h3>
<ul>
  <li>Build Num: 4107</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>BLOCKING_BUILD</td>
    <td>false</td>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_aue-gnu-12.1.0-anaconda3-serial_debug_shared_no-kokkos-arch_no-asan_no-complex_no-fpic_no-mpi_no-pt_no-rdc_no-uvm_deprecated-on_pr-framework</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request (Non-blocking)</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/cwpearson/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>cd82d2d165a0fb8665b558425f6ae2dd44ce888c</td>
  </tr>

  <tr>
    <td>TRILINOS_SRN_CONFIG</td>
    <td>true</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>93290bbeb6091234443086e46722672451183585</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: PR_cuda</h3>
<ul>
  <li>Build Num: 148</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>GENCONFIG_BUILD_NAME</td>
    <td>rhel8_sems-cuda-11.4.2-gnu-10.1.0-openmpi-4.1.6_release_static_Volta70_no-asan_complex_no-fpic_mpi_pt_no-rdc_no-uvm_deprecated-on_no-package-enables</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>13198</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_NODE_LABEL</td>
    <td>rhel8 [...]

2024-07-10 17:57 UTC, trilinos-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES!

2024-07-10 17:57 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-07-11 20:29 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-07-12 22:32 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-07-14 00:01 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-07-15 00:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-07-16 01:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2024-07-16 18:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-17 18:29 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-18 21:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-20 23:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-21 23:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-23 01:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-24 02:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-25 03:32 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-26 04:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-27 05:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-28 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-29 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-30 13:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-07-30 18:52 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2024-07-30 18:52 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2025-08-17 13:21 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection is Not Necessary for this Pull Request.

2025-08-18 16:47 UTC, jhux2 commented
@csiefer2 @cwpearson Still relevant, I think?

2025-09-13 22:42 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - GitHub reports Mergeable status = False

2026-07-27 17:24 UTC, cwpearson commented
Perhaps revisit this another time.

2026-07-27 17:24 UTC, closed without merging