8200 wintpetra
trilinos/Trilinos pull request #8204
Opened 2020-10-15 20:24 UTC by jrobcary

@trilinos/kokkos-kernels @trilinos/intrepid2 @trilinos/zoltan2

## Motivation
The goal of this pull request is to fix some compilation failures on Windows.  This is a work in progress, as the build on Windows is not yet working.  I was encouraged to submit this anyway to get some feedback as to whether I am going in the right direction.

## Stakeholder Feedback

## Testing

Is there a way to know which test corresponds to some source file?  In any case, the changes are all in #if blocks, so not likely to affect any tests run on Linux.

2020-10-15 21:14 UTC, kddevin reviewed
The zoltan2 changes are OK with me.  I cannot review the other packages.

Since KokkosKernels is a snap-shot into Trilinos, KokkosKernels changes might have to be coordinated with the Kokkos github repo.

2020-10-15 21:46 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2020-10-17 12:34 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2020-10-19 18:43 UTC, srajama1 reviewed
Please see my comment on Amesos2. Kokkos Kernels changes look ok to me, but we have no way to test it.

Can we get a corresponding PR on the kokkoskernel  repo as what lives in Trilinos is a snapshot of that ?

2020-10-19 18:43 UTC, srajama1 commented on packages/amesos2/src/Amesos2_Superlu_def.hpp
> +#if 0
This "if 0" worries me. We have to support older SuperLU and I am not sure this has been removed everywhere.

2020-10-19 18:43 UTC, srajama1 commented
Here is the repo for Kokkos Kernels https://github.com/kokkos/kokkos-kernels

2020-10-19 20:24 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2020-10-20 03:11 UTC, crtrott requested changes
We need to introduce the Kokkos changes first in Kokkos proper, and I am not confident they are kosher. We are testing Visual Studio as part of our PR testing and it works. My suspicion is that these changes here come from using the clang frontend in VS. Generally we need more information. I.e. what is the configuration here (the visual studio configuration) etc. .

2020-10-20 03:11 UTC, crtrott commented on packages/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
> +#ifndef _WIN32
What is the config here and why do we need this change? We are currently testing Kokkos with Visual Studio during PR testing and it passes. I'd prefer if we could fix this in Kokkos first and make sure we support the config.

2020-10-20 03:11 UTC, crtrott commented on packages/kokkos/core/src/impl/Kokkos_ChaseLev.hpp
> +#if 0 // clang-cl says atomic_compare_exchange_strong is ambiguous.
Again we are testing with visual studio during PR testing. I suppose we might not test clang-cl but the non-clang version of VS compiler but that one is a compiler we support. Does this change break that?

2021-04-27 19:43 UTC, kddevin commented
Despite the name of this PR, no Tpetra files were changed by the PR.  I will change the name to something more appropriate.
@ccober6 @jwillenbring  Perhaps this PR has some info relevant to today's SART discussion.

2021-04-27 19:48 UTC, jrobcary commented
This project is on hold while dealing with other priorities.  Will get 
back to it over the next few months.

On 4/27/21 1:43 PM, K Devine wrote:
>
> Despite the name of this PR, no Tpetra files were changed by the PR. I 
> will change the name to something more appropriate.
> @ccober6 <https://github.com/ccober6> @jwillenbring 
> <https://github.com/jwillenbring> Perhaps this PR has some info 
> relevant to today's SART discussion.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/trilinos/Trilinos/pull/8204#issuecomment-827876000>, 
> or unsubscribe 
> <https://github.com/notifications/unsubscribe-auth/AAK72TH6HPXN7OC4CPY2BYDTK4HXDANCNFSM4SSOY2ZA>.
>

2021-05-11 11:52 UTC, closed without merging