Turn on PIC for all ATDM builds
trilinos/Trilinos pull request #8760
Opened 2021-02-15 21:16 UTC by sebrowne

EMPIRE was doing this (effectively), now SPARC wants it as well.  I
changed to the CMake method for PIC, it seemed to work when I tested it
with SPARC on CEE and ATS2 (the flag isn't alwauys -fPIC, also this
applies it to other languages).

@trilinos/framework

2021-02-15 21:17 UTC, sebrowne commented
@bartlettroscoe @jmgate 

I used this approach (CMAKE_POSITION_INDEPENDENT_CODE) in the SPARC configure scripts, and it seemed to work, without having to manually manipulate the flags.  But I'll defer to your knowledge Ross in particular if there are any issues with it.  I turned it on for everything (defaulted, still based on the ATDM configure option), and got rid of the EMPIRE-specific code that did it too.

I'm working on getting this tested now, if it works on CTS1, I'd like to push it.

2021-02-15 21:25 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           WARNING: NO REVIEWERS HAVE BEEN REQUESTED FOR THIS PULL REQUEST!

2021-02-15 21:32 UTC, jmgate commented
Looks fine to me, but I'll defer to @bartlettroscoe or @e10harvey.

2021-02-15 21:45 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2021-02-15 21:47 UTC, bartlettroscoe requested changes
Need to likely add a `no-fpic` option and update the documentation at:

* https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/README.md#fpic

as well.

Otherwise, the `fpic` keyword option just needs to be removed and `-fPIC` should just be hard-coded in the compiler flags.  But I suspect that it would be best to provide and option to disable setting `-fPIC` in some situations so I suspect that adding a `no-fpic` keyword with the default being changed as per in this PR is the right thing to do.

2021-02-15 21:49 UTC, sebrowne commented
Okay, I'll take care of it.  Also I made a syntax error discovered upon testing, but the meat of the change appears to work once I fixed that.

2021-02-15 21:55 UTC, bartlettroscoe commented
> Okay, I'll take care of it. Also I made a syntax error discovered upon testing, but the meat of the change appears to work once I fixed that.

 Thanks @sebrowne.   And I suspect that setting `CMAKE_POSITION_INDEPENDENT_CODE` is far better than directly setting `-fPIC`.  I was not aware that option even existed in CMake.    Looks like that option has been part of CMake since at least CMake 3.10.

2021-02-15 22:02 UTC, sebrowne commented
I just discovered it in the last week or so, and when I tested it seemed to work, so I figured it was better that CMake maintain the list of flags instead of me :D

2021-02-15 22:03 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS NOT BEEN REVIEWED YET!

2021-02-15 22:04 UTC, bartlettroscoe requested changes
@sebrowne, looks good.  The last thing is to document that 'fpic' is the default in all builds.  Then this looks good to me.

2021-02-15 22:04 UTC, bartlettroscoe commented on cmake/std/atdm/README.md
> +* `fpic`: Turn on `CMAKE_POSITION_INDEPENDENT_CODE`
Can we mention that `fpic` is the default option on all platforms?  Otherwise, the documentation is not clear here.

2021-02-15 22:04 UTC, bartlettroscoe commented on cmake/std/atdm/utils/set_build_options.sh
> +elif atdm_match_buildname_keyword no-fpic; then
This needs to be moved before the match for 'fpic' or it will not ever match 'no-fpic'.

2021-02-15 22:13 UTC, bartlettroscoe commented
@sebrowne and @jmgate, I just remembered, the unit tests for this will need to be updated as well.  See:

*  https://github.com/trilinos/Trilinos/blob/develop/cmake/std/atdm/test/unit_tests/set_build_options_unit_tests.sh

(The PR testing will catch this.)

2021-02-15 22:29 UTC, bartlettroscoe approved these changes
Looks good to me.  Thanks @sebrowne!

2021-02-15 22:43 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ bartlettroscoe ]!

2021-02-15 22:45 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 3595</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 1206</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 1699</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 9056</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_10.1.105</h3>
<ul>
  <li>Build Num: 521</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 1887</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_python_3</h3>
<ul>
  <li>Build Num: 4568</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (sebrowne/Trilinos)</dt>
  <ul>
    <li>Branch: sebrown/always_PIC</li>
    <li>SHA: 0835c4877db2d12d987166c9fd555b53bc98db5e</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: sebrowne
</details>

2021-02-15 22:50 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 3595</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 1206</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 1699</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 9056</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_10.1.105</h3>
<ul>
  <li>Build Num: 521</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 1887</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_python_3</h3>
<ul>
  <li>Build Num: 4568</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: AUTOMERGE;ATDM Config;client: EMPIRE;client: SPARC</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>8760</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>sebrown/always_PIC</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/sebrowne/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>0835c4877db2d12d987166c9fd555b53bc98db5e</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>ff88a3201c8fb37ed587e17b434bbe9b1c0a5c22</td>
  </tr>
</table>
</details>


<br>[CDash Test Results for PR# 8760.](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=PR-8760-test&field2=buildstarttime&compare2=84&value2=NOW
)<br>

2021-02-15 22:50 UTC, trilinos-autotester commented
Status Flag 'Pre-Merge Inspection' - SUCCESS: The last commit to this Pull Request has been INSPECTED AND APPROVED by [ bartlettroscoe ]!

2021-02-15 22:50 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Pull Request will be Automerged

2021-02-15 22:50 UTC, merged

2021-02-15 22:50 UTC, trilinos-autotester commented
Merge on Pull Request# 8760: IS A SUCCESS - Pull Request successfully merged

2021-03-18 14:34 UTC, e10harvey reviewed
Thanks, @sebrowne !

2021-03-18 14:34 UTC, e10harvey commented on cmake/std/atdm/test/unit_tests/set_build_options_unit_tests.sh
> +
Missing tests for `fpic`?

2021-03-18 14:34 UTC, e10harvey commented on cmake/std/atdm/utils/set_build_options.sh
> +export ATDM_CONFIG_FPIC=ON
Corresponding unset missing but has been added since this merged.