Some small Hash and Sort improvements
trilinos/Trilinos pull request #9794
Opened 2021-10-08 19:15 UTC by bavier

@trilinos/epetra
@trilinos/tpetra
@trilinos/zoltan

## Motivation

This PR attempts to upstream some small performance improvements to Epetra and Tpetra sort utilities and a hash-map in Zoltan.

## Testing
The routines this PR touches are exercised by many of the unit tests of the affected packages.

2021-10-08 20:30 UTC, jhux2 commented
@trilinos/epetra @trilinos/zoltan @trilinos/tpetra

2021-12-15 00:02 UTC, kddevin requested changes
@bavier  Thanks for the contributions.
Can you give us some performance numbers involving these changes?   
I can find Ciura's gap sequence up to 1750 online; how did you generate the rest of the numbers?
What happens if someone tries to sort 135M values.  While doing so may not be advised with shell sort, there are no guards to prevent it in the new implementation.
Is there a better starting value for c?  Many uses of sort2 are sorting short lists, e.g., local column indices for a given row.

2021-12-15 00:42 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           THE LAST COMMIT TO THIS PULL REQUEST HAS BEEN REVIEWED, BUT NOT ACCEPTED OR REQUIRES CHANGES

2021-12-15 01:54 UTC, bavier commented
@kddevin This excerpt from one of the commit messages:

> E.g. trilinoscouplings/examples/scaling/Poisson.cpp run with -n128
-N16 and a 200x200x200 mesh with scotch-based load-balancing went from
95.7s runtime to 86.9s (6% speedup overall, 8.8% spent in
Epetra_Util::Sort to 5.2%).

As far as how the sequence was derived: at the time I developed this patch (at least 7 years ago) I believe I had a performance test harness where for those past 2000 or so I tested several values in the area around what a linear recurrence would produce.  But I can't find that test harness, and I don't recall how much having the larger gap numbers made on the final performance of very large arrays.  Ultimately, I recall that any gap sequence was far better than the `n/2` sequence, but I would need to do another analysis to convince myself again that the larger gap elements were truly beneficial.

Each gap value is used as a the stride for a sublist sort.  There's no "greatest length" that can be handled.  For shorter lists, the larger gap values are skipped via the `j<max` condition.

2023-03-25 12:25 UTC, closed without merging