Spack environment
trilinos/Trilinos pull request #9989
Opened 2021-12-06 03:41 UTC by fryeguy52

@trilinos/framework 

## Motivation
This is the begging of work on the trilinos spack package

see: TRILFRAME-199

2021-12-07 05:02 UTC, trilinos-autotester commented
Status Flag 'Pre-Test Inspection' - Auto Inspected - Inspection Is Not Necessary for this Pull Request.

2021-12-07 05:02 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver</h3>
<ul>
  <li>Build Num: 178</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver_uvm_off</h3>
<ul>
  <li>Build Num: 114</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li>Branch: spack-environment</li>
    <li>SHA: b49f863bdd4bdedc4380e7546de4ca35db991ea7</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: fryeguy52
</details>

2021-12-07 05:04 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver</h3>
<ul>
  <li>Build Num: 178</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver_uvm_off</h3>
<ul>
  <li>Build Num: 114</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6129</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 3661</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4181</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11312</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4111</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 746</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
   [...]

2021-12-07 05:07 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver</h3>
<ul>
  <li>Build Num: 178</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver_uvm_off</h3>
<ul>
  <li>Build Num: 114</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6129</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 3661</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4181</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11312</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4111</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 746</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  [...]

2021-12-07 05:07 UTC, trilinos-autotester commented
Status Flag 'Pre-Merge Inspection' - - This Pull Request Requires Inspection... The code must be inspected by a member of the Team before Testing/Merging
           NO REVIEWS HAVE BEEN PERFORMED ON THIS PULL REQUEST!

2021-12-07 05:07 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-12-08 07:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-12-09 10:39 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-12-10 10:39 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-12-11 01:03 UTC, william76 commented
@fryeguy52 The convention in Trilinos for issues and Pull Requests is to format the title as: `<TeamName>: <title>`

For Framework, these should be prefixed as `Framework: <title>`

2021-12-11 14:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-12-12 14:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2021-12-13 05:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-13 16:18 UTC, e10harvey requested changes
Thanks, @fryeguy52 ! Please change `root: ...` to `root: $HOME/trilinos-spack-test-install`.

Will `install_missing_compilers: true` attempt to load the gcc/10.1.10 module?

2021-12-13 16:31 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-14 23:34 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-16 02:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-17 04:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-18 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-19 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-20 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-22 14:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-23 15:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-24 15:30 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-25 15:30 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-26 15:30 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-27 15:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-28 15:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-29 15:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-30 15:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2021-12-31 15:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-01 16:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-02 16:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-03 16:19 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-04 16:30 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-04 20:38 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-01-04 20:39 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver</h3>
<ul>
  <li>Build Num: 333</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver_uvm_off</h3>
<ul>
  <li>Build Num: 269</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li>Branch: spack-environment</li>
    <li>SHA: b49f863bdd4bdedc4380e7546de4ca35db991ea7</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: fryeguy52
</details>

2022-01-04 20:40 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver</h3>
<ul>
  <li>Build Num: 333</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver_uvm_off</h3>
<ul>
  <li>Build Num: 269</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6291</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 3818</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4338</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11449</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4247</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li [...]

2022-01-04 20:43 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver</h3>
<ul>
  <li>Build Num: 333</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_cuda_weaver_uvm_off</h3>
<ul>
  <li>Build Num: 269</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6291</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 3818</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4338</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11449</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4247</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>
</details>


<br>[CDash Test Results for PR# 9989.](https://testing.sandia.gov/cdash/ind [...]

2022-01-04 20:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-01-06 04:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-01-07 05:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-01-08 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-01-09 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-01-10 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-01-10 20:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-11 22:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-13 01:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-14 02:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-16 02:31 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-17 02:50 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-18 03:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-19 04:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-20 05:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-22 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-23 14:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-24 16:34 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-27 06:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-28 14:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-01-30 19:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-01 02:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-02 04:07 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-03 05:31 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-04 10:39 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-05 14:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-06 14:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-07 14:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-08 18:18 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-09 19:28 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-12 03:19 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-14 14:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-15 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-16 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-02-16 20:24 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - User Requested Retest - Label AT: RETEST will be reset after testing.

2022-02-16 20:26 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6650</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4170</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4692</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11776</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4566</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1130</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 335</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li>Branch: spack-environment</li>
    <li>SHA: b49f863bdd4bdedc4380e7546de4ca35db991ea7</li>
    <li>Mode: TES [...]

2022-02-16 20:31 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 2 Hrs 30 Mins. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6650</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4170</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4692</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11776</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4566</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1130</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 335</li>
  <li>Status: FAILED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>
</ [...]

2022-02-16 23:48 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6656</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4176</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4698</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11782</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4571</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1135</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 342</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li>Branch: spack-environment</li>
    <li>SHA: b49f863bdd4bdedc4380e7546de4ca35db991ea7</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: fryeguy52
</details>

2022-02-17 06:12 UTC, trilinos-autotester commented
NOTICE: The AutoTester has encountered an internal error (usually a Communications Timeout), testing will be restarted, previous tests may still be running but will be ignored by the AutoTester...

2022-02-17 06:27 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Failure: Timed out waiting for job Trilinos_pullrequest_clang_10.0.0 to start: Total Wait = 603
- Other jobs have been previously started - We must stop them...
- Terminating Build #6659 of Jenkins job Trilinos_pullrequest_gcc_8.3.0 on Jenkins server at https://ascic-jenkins.sandia.gov
- Terminating Build #4179 of Jenkins job Trilinos_pullrequest_gcc_7.2.0_serial on Jenkins server at https://ascic-jenkins.sandia.gov
- Terminating Build #4701 of Jenkins job Trilinos_pullrequest_gcc_7.2.0_debug on Jenkins server at https://ascic-jenkins.sandia.gov
- Terminating Build #11785 of Jenkins job Trilinos_pullrequest_intel_17.0.1 on Jenkins server at https://ascic-jenkins.sandia.gov

2022-02-17 11:00 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6668</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4188</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4710</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11794</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4575</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1139</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 347</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li>Branch: spack-environment</li>
    <li>SHA: b49f863bdd4bdedc4380e7546de4ca35db991ea7</li>
    <li>Mode: TEST_REPO</li>
  </ul>
</dl>

Pull Request Author: fryeguy52
</details>

2022-02-17 23:56 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Error: Jenkins Jobs - Timed out waiting for ALL builds to complete: Total Wait = 25260; Max Timeout = 25200

2022-02-17 23:56 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: 1 or more Jobs FAILED

Note: Testing will normally be attempted again in approx. 2 Hrs 30 Mins. If a change to the PR source branch occurs, the testing will be attempted again on next available autotester run.

<details>
<summary>
  <b>Pull Request Auto Testing has FAILED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6668</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4188</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4710</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11794</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4575</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1139</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 347</li>
  <li>Status: ERROR</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td></td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>
</details>


<details>
<summary>
  <b>Console Output (last 100 lines) : Trilino [...]

2022-02-22 14:26 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Testing Jenkins Projects:

<details>
<summary>
  <b>Pull Request Auto Testing STARTING</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6749</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4267</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4787</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11866</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4624</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1187</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 399</li>
  <li>Status: STARTED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Using Repos:</h2>

<dl>
  <dt>Repo: TRILINOS (fryeguy52/Trilinos)</dt>
  <ul>
    <li>Branch: spack-environment</li>
    <li>SHA: b49f863bdd4bdedc4380e7546de4ca35db991ea7</li>
    <li>Mode: TES [...]

2022-02-22 16:49 UTC, trilinos-autotester commented
Status Flag 'Pull Request AutoTester' - Jenkins Testing: all Jobs PASSED

<details>
<summary>
  <b>Pull Request Auto Testing has PASSED</b> (click to expand)
</summary>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_8.3.0</h3>
<ul>
  <li>Build Num: 6749</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_serial</h3>
<ul>
  <li>Build Num: 4267</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_gcc_7.2.0_debug</h3>
<ul>
  <li>Build Num: 4787</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_intel_17.0.1</h3>
<ul>
  <li>Build Num: 11866</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: Trilinos_pullrequest_clang_10.0.0</h3>
<ul>
  <li>Build Num: 4624</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: python-3</h3>
<ul>
  <li>Build Num: 1187</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>

<h2>Build Information</h2>
<h3>Test Name: _cuda_10.1.243</h3>
<ul>
  <li>Build Num: 399</li>
  <li>Status: PASSED</li>
</ul>

<h4>Jenkins Parameters</h4>
<table>
  <tr>
    <th>Parameter Name</th>
    <th>Value</th>
  </tr>

  <tr>
    <td>FORCE_CLEAN</td>
    <td>true</td>
  </tr>

  <tr>
    <td>PR_LABELS</td>
    <td>AT: RETEST</td>
  </tr>

  <tr>
    <td>PULLREQUESTNUM</td>
    <td>9989</td>
  </tr>

  <tr>
    <td>PULLREQUEST_CDASH_TRACK</td>
    <td>Pull Request</td>
  </tr>

  <tr>
    <td>TEST_REPO_ALIAS</td>
    <td>TRILINOS</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_BRANCH</td>
    <td>spack-environment</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_REPO</td>
    <td>https://github.com/fryeguy52/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_SOURCE_SHA</td>
    <td>b49f863bdd4bdedc4380e7546de4ca35db991ea7</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_BRANCH</td>
    <td>develop</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_REPO</td>
    <td>https://github.com/trilinos/Trilinos</td>
  </tr>

  <tr>
    <td>TRILINOS_TARGET_SHA</td>
    <td>444a5d09b62915536be6177e2c7dc465ed281246</td>
  </tr>
</table>
</details>


<br>[CDash Test Results for PR# 9989.](https://testing.sandia.gov/cdash/index.php?project=Trilinos&filtercombine=and&filtercombine=and&filtercombine=and&filtercombine=and&filtercombin [...]

2022-02-22 16:49 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-23 20:07 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-24 21:27 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-26 21:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-27 21:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However Inspection must be performed before merge can occur...

2022-02-28 17:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-01 18:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-04 05:53 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-05 14:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-06 14:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-07 14:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-08 21:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-10 00:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-11 00:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-12 05:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-13 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-14 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-15 15:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-16 15:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-17 19:49 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-19 03:35 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-20 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-21 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-21 13:09 UTC, jwillenbring commented
@fryeguy52 did you see the changes suggested by @e10harvey ?

2022-03-23 01:18 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-24 03:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-25 16:26 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-26 21:18 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-27 21:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-29 06:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-03-31 00:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-01 01:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-02 01:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-03 01:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-04 01:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-05 11:38 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-06 12:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-07 17:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-09 16:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-10 16:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-11 16:39 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-12 16:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-13 17:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-14 17:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-15 17:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-18 17:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-19 17:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-20 19:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-22 12:33 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-23 22:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-25 02:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-26 04:49 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-27 04:51 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-28 05:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-04-29 21:55 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-01 02:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-02 07:52 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-03 18:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-05 05:53 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-07 02:49 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-08 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-09 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-10 16:08 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-11 23:51 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-13 03:40 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-14 19:51 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-15 20:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-18 08:19 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-19 09:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-21 09:27 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-22 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-23 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-25 01:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-26 05:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-27 06:32 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-28 13:37 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-29 14:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-30 14:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-05-31 14:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-03 20:47 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-05 04:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-06 04:28 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-07 04:52 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-08 07:08 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-09 09:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-10 10:45 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-11 23:51 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-13 00:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-14 11:52 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-17 23:53 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-19 00:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-20 00:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-21 00:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-22 03:49 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-23 05:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-24 05:59 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-27 12:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-28 12:57 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-06-29 15:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-02 00:21 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-03 03:46 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-04 04:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-05 04:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-06 09:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-07 10:41 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-08 19:57 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-09 20:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-10 20:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-11 20:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-12 20:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-13 22:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-14 23:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-15 23:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-16 23:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-17 23:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-18 23:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-19 23:57 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-21 02:38 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-22 12:18 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-23 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-24 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-28 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-29 14:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-30 14:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-07-31 14:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-01 14:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-02 16:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-04 05:08 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-06 05:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-08 04:54 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-09 23:53 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-11 16:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-13 08:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-15 00:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-16 20:15 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-23 16:07 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-25 12:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-26 18:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-27 18:26 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-28 18:26 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-29 18:46 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-30 18:53 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-08-31 19:21 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-01 20:17 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-02 22:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-03 22:26 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-04 22:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-05 22:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-07 04:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-08 10:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-09 13:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-10 15:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-11 15:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-12 23:53 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-16 14:30 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-17 17:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-18 17:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-19 18:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-20 18:47 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-21 20:34 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-23 08:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-24 13:15 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-25 13:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-26 15:55 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-27 17:33 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-29 05:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-09-30 10:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-01 13:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-02 13:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-03 13:46 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-04 18:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-06 05:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-07 05:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-08 13:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-09 13:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-11 18:33 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-12 21:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-13 21:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-14 21:29 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-15 21:46 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-16 22:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-17 22:12 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-19 02:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-20 07:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-21 10:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-22 17:02 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-23 17:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-24 21:46 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-26 07:20 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-27 10:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-28 13:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-29 13:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-30 13:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-10-31 13:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-01 13:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-02 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-03 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-08 03:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-09 04:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-10 05:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-11 10:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-12 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-13 14:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-14 14:09 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-15 16:55 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-16 17:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-17 22:12 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-18 22:33 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-19 22:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-20 22:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-21 23:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-22 23:55 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-24 00:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-25 00:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-26 01:17 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-27 01:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-28 01:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-29 02:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-11-30 16:31 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-01 16:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-02 22:18 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-03 23:56 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-05 00:02 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-06 07:10 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-07 11:02 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-08 13:59 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-10 14:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-11 14:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-13 15:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-14 21:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-16 06:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-17 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-18 16:40 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-19 16:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-20 16:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-21 17:37 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-22 20:49 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-23 21:02 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-24 21:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-25 21:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-26 21:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-27 22:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-28 22:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-29 22:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-30 22:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2022-12-31 22:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-01 22:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-02 23:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-04 03:34 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-05 04:16 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-06 08:24 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-07 15:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-09 04:16 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-10 05:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-11 05:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-12 11:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-13 13:59 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-14 14:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-15 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-16 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-17 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-18 22:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-19 22:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-20 22:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-21 22:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-22 22:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-23 23:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-24 23:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-26 00:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-27 00:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-28 00:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-29 01:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-30 01:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-01-31 01:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-01 06:36 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-02 20:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-03 20:11 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-04 20:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-05 20:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-06 23:45 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-08 17:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-09 18:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-10 18:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-11 18:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-12 18:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-13 18:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-14 19:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-15 22:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-16 22:26 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-17 22:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-18 23:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-19 23:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-21 10:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-22 21:00 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-24 01:48 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-25 02:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-26 02:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-27 02:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-02-28 02:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-01 04:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-02 05:13 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-03 09:08 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-04 14:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-05 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-06 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-07 15:55 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-08 16:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-09 17:09 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-10 19:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-11 19:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-12 19:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-13 19:45 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-15 00:20 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-16 07:25 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-17 09:58 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-18 13:04 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-19 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-20 13:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-22 14:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-23 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-24 14:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-25 15:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-26 15:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-27 15:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-28 17:39 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-29 23:16 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-30 23:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-03-31 23:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-01 23:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-03 00:02 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-04 00:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-05 01:57 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-06 02:14 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-07 02:22 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-08 13:05 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-09 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-10 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-11 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-13 17:55 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-14 18:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-17 12:56 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-20 13:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-21 13:06 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-22 13:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-23 13:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-24 13:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-25 14:03 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-27 14:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-28 14:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-29 18:31 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-04-30 18:42 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-01 19:09 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-02 20:30 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-03 23:44 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-05 00:02 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-06 00:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-07 00:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-08 00:23 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2023-05-09 00:43 UTC, trilinos-autotester commented
All Jobs Finished; status = PASSED, However PR is now STALE, and must be retested.  Set the AT: RETEST Label to force retest....

2024-09-16 13:26 UTC, closed without merging